### ISSUE TITLE
Adding PHP Intelephense

### ISSUE THREAD

**Issue by xRealNeon** [onecentlin/laravel-extension-pack-vscode#10]
Can you add [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) to the extension pack?

**Comment by onecentlin** [comment]
@xRealNeon PHP Intelephense has been in my another vscode extension: [PHP Productive Pack](https://marketplace.visualstudio.com/items?itemName=onecentlin.php-productive-pack)
