### ISSUE TITLE
Everytime I start vscode I get a VS Live Share installed notification...

### ISSUE THREAD

**Issue by ryanmortier** [onecentlin/laravel-extension-pack-vscode#3]
I don't remember installing this extension but when I go to disable it it errors out saying Laravel Extension Pack depends on this extension. Why does Laravel Extension Pack depend on VS Live Share?

**Comment by onecentlin** [comment]
@ryanmortier This issue has been fixed. Please update to v0.3.1, thanks!

**Comment by onecentlin** [comment]
@ryanmortier Please update VS Code to ^1.26, and update this extension to v0.4.0. Thanks.

**Comment by ryanmortier** [comment]
Thanks.
