### ISSUE TITLE
Remove Live Share from the extension pack

### ISSUE THREAD

**Issue by NatoBoram** [onecentlin/laravel-extension-pack-vscode#7]
[Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) has nothing to do with Laravel development. This is out of scope for the extension.

Users wishing to set-up Live Share can do so by installing the extension by themselves.

**Comment by onecentlin** [comment]
@NatoBoram Removed in v1.0.0 version. Enjoy!
