### ISSUE TITLE
Please add "laravel-goto-controller" into this pack.

### ISSUE THREAD

**Issue by bluedasher13** [onecentlin/laravel-extension-pack-vscode#8]
Please add [**`laravel-goto-controller`** (_`stef-k.laravel-goto-controller`_)](https://marketplace.visualstudio.com/items?itemName=stef-k.laravel-goto-controller) into this pack.

**Comment by onecentlin** [comment]
@bluedasher13 Added in v1.0.0 version. Enjoy!
